algoritmo "Realizando as 4 operações básicas"
// Realizando as 4 operações básicas
var
   valorA,valorB : inteiro
inicio
   escreval("Digite um valor")
   leia(valorA)
   
   escreval("Digite outro valor")
   leia(valorB)
// Adição
   escreval("Adição", (valorA + valorB))

// Subtração
   escreval("Subtração", (valorA - valorB))
   
// Multiplicação
   escreval("Multiplicação", (valorA * valorB))
   
// Divisão
   escreval("Divisão", (valorA / valorB))

   
fimalgoritmo
