algoritmo "Consumo médio de um automóvel"

var
   fatorA : real
   fatorB: real
   fatorC: real
inicio
// Fornecendo os Km rodados
   escreval("Digite a distância percorrida em Km")
   leia(fatorA)
   
// Fornecendo o combustivel gasto em L
   escreval(" Digite o total de combustivel gasto em L")
   leia(fatorB)
   
// Consumo médio
   escreval("O consumo médio foi de", (fatorA / fatorB), " Km/L")
fimalgoritmo
