algoritmo "Faça um algoritmo que receba um número e diga se este número está no intervalo entre 100 e 200"

var
   valorX : real
inicio
   escreval("Digite um número")
   leia(valorX)
// Definindo se o número está entre 100 e 200
   se (valorX>=100) e (valorX<=200) entao
   escreval("O número está entre 100 e 200")
   senao
   escreval("O número não está entre 100 e 200")
   fimse
fimalgoritmo
