algoritmo " Escrever um algoritmo que leia dois valores inteiros distintos e informe qual é o maior

var
   valorA : inteiro
   valorB : inteiro
inicio
// Primeiro valor
   escreval("Digite um número")
   leia(valorA)
// Segundo valor
   escreval("Digite outro número distinto")
   leia(valorB)
//Definindo o maior
   se valorA>valorB entao
   escreval("O maior é", (valorA))
   senao
   escreval("O maior é", (valorB))
   fimse


fimalgoritmo
