algoritmo "Escreva um algoritmo para ler as dimensões de um retângulo (base e altura), calcular e escrever a área do retângulo. "


var
   base,altura,area: real
inicio

   escreval("Digite a dimensão da base do retângulo: ")
   leia(base)
      escreval("Digite a dimensão da altura do retângulo: ")
      leia(altura)
      
      area<- (base*altura)
      escreval("A área do retângulo(base x altura) é de: ",(area),"(Unidade de medida correspondente)")
fimalgoritmo
